# Generated by Django 3.0.4 on 2020-03-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infodata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_id', models.CharField(max_length=100)),
                ('info_pw', models.CharField(max_length=100)),
            ],
        ),
    ]
